// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"forum/service/comment/cmd/rpc/internal/logic"
	"forum/service/comment/cmd/rpc/internal/svc"
	"forum/service/comment/cmd/rpc/pb"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

// 创建评论
func (s *CommentServer) CreateComment(ctx context.Context, in *pb.CreateCommentReq) (*pb.CreateCommentResp, error) {
	l := logic.NewCreateCommentLogic(ctx, s.svcCtx)
	return l.CreateComment(in)
}

// 展示评论
func (s *CommentServer) ShowComment(ctx context.Context, in *pb.ShowCommentReq) (*pb.ShowCommentResp, error) {
	l := logic.NewShowCommentLogic(ctx, s.svcCtx)
	return l.ShowComment(in)
}
