// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postFieldNames          = builder.RawFieldNames(&Post{})
	postRows                = strings.Join(postFieldNames, ",")
	postRowsExpectAutoSet   = strings.Join(stringx.Remove(postFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postRowsWithPlaceHolder = strings.Join(stringx.Remove(postFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheForumPostIdPrefix = "cache:forum:post:id:"
)

type (
	postModel interface {
		Insert(ctx context.Context, data *Post) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Post, error)
		Update(ctx context.Context, data *Post) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPostModel struct {
		sqlc.CachedConn
		table string
	}

	Post struct {
		Id        int64     `db:"id"`
		Title     string    `db:"title"`   // 标题
		Content   string    `db:"content"` // 内容
		UserId    int64     `db:"user_id"` // 用户id
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPostModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPostModel {
	return &defaultPostModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`post`",
	}
}

func (m *defaultPostModel) Delete(ctx context.Context, id int64) error {
	forumPostIdKey := fmt.Sprintf("%s%v", cacheForumPostIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, forumPostIdKey)
	return err
}

func (m *defaultPostModel) FindOne(ctx context.Context, id int64) (*Post, error) {
	forumPostIdKey := fmt.Sprintf("%s%v", cacheForumPostIdPrefix, id)
	var resp Post
	err := m.QueryRowCtx(ctx, &resp, forumPostIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, data *Post) (sql.Result, error) {
	forumPostIdKey := fmt.Sprintf("%s%v", cacheForumPostIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, postRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId)
	}, forumPostIdKey)
	return ret, err
}

func (m *defaultPostModel) Update(ctx context.Context, data *Post) error {
	forumPostIdKey := fmt.Sprintf("%s%v", cacheForumPostIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.Id)
	}, forumPostIdKey)
	return err
}

func (m *defaultPostModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheForumPostIdPrefix, primary)
}

func (m *defaultPostModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostModel) tableName() string {
	return m.table
}
