// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"forum/service/comment/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建评论
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: createCommentHandler(serverCtx),
			},
			{
				// 展示评论
				Method:  http.MethodGet,
				Path:    "/comment/:id",
				Handler: ShowCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
