// Code generated by goctl. DO NOT EDIT.
package types

type CreateCommentReq struct {
	UserId int64  `json:"userId"`
	Desc   string `json:"desc"`
}

type CreateCommentResp struct {
	Id string `json:"id"`
}

type ShowCommentReq struct {
}

type ShowCommentResp struct {
	UserId int64  `json:"userId"`
	Desc   string `json:"desc"`
}
