// Code generated by goctl. DO NOT EDIT.
package types

type CreateCommentReq struct {
	UserId int64  `json:"userId"`
	Desc   string `json:"desc"`
}

type CreateCommentResp struct {
	Id int64 `json:"id"`
}

type ShowCommentReq struct {
	Id int64 `path:"id"` // 路径参数id 也要写出来
}

type ShowCommentResp struct {
	UserId int64  `json:"userId"`
	Desc   string `json:"desc"`
}

type UploadRes struct {
	Code int `json:"code"`
}
