// Code generated by goctl. DO NOT EDIT.
package types

type PostCreateRequest struct {
	UserId  int64  `json:"user_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PostCreateResponse struct {
	Id int64 `json:"id"`
}
